import { lato, kanit } from "@/styles/fonts";
import "@/styles/globals.scss";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }) => {
  return (
    <html lang="pt-br" suppressHydrationWarning={true}>
      <body className={`${lato.variable} ${kanit.variable}`}>{children}</body>
    </html>
  );
}

export default RootLayout;