// Catálogo de elementos Lattes extraídos do XSD CurriculoLattes_12_09_2022.
// Cada entrada define o elemento selecionável no editor de Ficha de Avaliação:
//   label      → nome legível para o select
//   path       → caminho no XML do Lattes (usado no campo path do schema)
//   tagLattes  → tag do elemento container (usado no campo tagLattes do schema)
//   attrs      → atributos disponíveis para filtros e campos (derivados via mergeAttrs:true do xml2js)
//   enumValues → atributos com valores fechados definidos no XSD (campo → array de valores)

export const LATTES_ELEMENTS = [
  {
    label: "Artigos Publicados",
    path: "CURRICULO-VITAE/PRODUCAO-BIBLIOGRAFICA/ARTIGOS-PUBLICADOS",
    tagLattes: "ARTIGOS-PUBLICADOS",
    attrs: [
      "NATUREZA", "TITULO-DO-ARTIGO", "ANO-DO-ARTIGO", "PAIS-DE-PUBLICACAO",
      "IDIOMA", "DOI", "TITULO-DO-ARTIGO-INGLES", "TITULO-DO-PERIODICO-OU-REVISTA",
      "ISSN", "QUALIS", "VOLUME", "FASCICULO", "SERIE", "PAGINA-INICIAL",
      "PAGINA-FINAL", "LOCAL-DE-PUBLICACAO",
    ],
    enumValues: {
      "NATUREZA": ["COMPLETO", "RESUMO", "NAO_INFORMADO"],
    },
  },
  {
    label: "Trabalhos em Eventos",
    path: "CURRICULO-VITAE/PRODUCAO-BIBLIOGRAFICA/TRABALHOS-EM-EVENTOS",
    tagLattes: "TRABALHOS-EM-EVENTOS",
    attrs: [
      "NATUREZA", "TITULO-DO-TRABALHO", "ANO-DO-TRABALHO", "PAIS-DO-EVENTO",
      "IDIOMA", "DOI", "CLASSIFICACAO-DO-EVENTO", "NOME-DO-EVENTO",
      "CIDADE-DO-EVENTO", "ANO-DE-REALIZACAO", "TITULO-DOS-ANAIS-OU-PROCEEDINGS",
      "VOLUME", "FASCICULO", "SERIE", "PAGINA-INICIAL", "PAGINA-FINAL",
      "ISBN", "NOME-DA-EDITORA", "CIDADE-DA-EDITORA",
    ],
    enumValues: {
      "NATUREZA": ["COMPLETO", "RESUMO", "RESUMO_EXPANDIDO", "NAO_INFORMADO"],
      "CLASSIFICACAO-DO-EVENTO": ["INTERNACIONAL", "NACIONAL", "REGIONAL", "LOCAL", "NAO_INFORMADO"],
    },
  },
  {
    label: "Livros Publicados ou Organizados",
    path: "CURRICULO-VITAE/PRODUCAO-BIBLIOGRAFICA/LIVROS-E-CAPITULOS/LIVROS-PUBLICADOS-OU-ORGANIZADOS",
    tagLattes: "LIVROS-PUBLICADOS-OU-ORGANIZADOS",
    attrs: [
      "TIPO", "NATUREZA", "TITULO-DO-LIVRO", "ANO", "PAIS-DE-PUBLICACAO",
      "IDIOMA", "DOI", "NUMERO-DE-VOLUMES", "NUMERO-DE-PAGINAS", "ISBN",
      "NUMERO-DA-EDICAO-REVISAO", "NUMERO-DA-SERIE", "CIDADE-DA-EDITORA",
      "NOME-DA-EDITORA",
    ],
    enumValues: {
      "TIPO": ["LIVRO_PUBLICADO", "LIVRO_ORGANIZADO_OU_EDICAO", "NAO_INFORMADO"],
      "NATUREZA": ["COLETANEA", "TEXTO_INTEGRAL", "VERBETE", "ANAIS", "CATALOGO", "ENCICLOPEDIA", "LIVRO", "OUTRA", "PERIODICO", "NAO_INFORMADO"],
    },
  },
  {
    label: "Capítulos de Livros Publicados",
    path: "CURRICULO-VITAE/PRODUCAO-BIBLIOGRAFICA/LIVROS-E-CAPITULOS/CAPITULOS-DE-LIVROS-PUBLICADOS",
    tagLattes: "CAPITULOS-DE-LIVROS-PUBLICADOS",
    attrs: [
      "TIPO", "TITULO-DO-CAPITULO-DO-LIVRO", "ANO", "PAIS-DE-PUBLICACAO",
      "IDIOMA", "DOI", "TITULO-DO-LIVRO", "NUMERO-DE-VOLUMES", "PAGINA-INICIAL",
      "PAGINA-FINAL", "ISBN", "ORGANIZADORES", "NUMERO-DA-EDICAO-REVISAO",
      "NUMERO-DA-SERIE", "CIDADE-DA-EDITORA", "NOME-DA-EDITORA",
    ],
    enumValues: {},
  },
  {
    label: "Tradução",
    path: "CURRICULO-VITAE/PRODUCAO-BIBLIOGRAFICA/DEMAIS-TIPOS-DE-PRODUCAO-BIBLIOGRAFICA/TRADUCAO",
    tagLattes: "TRADUCAO",
    attrs: [
      "NATUREZA", "TITULO", "ANO", "PAIS-DE-PUBLICACAO", "IDIOMA", "DOI",
      "NOME-DO-AUTOR-TRADUZIDO", "TITULO-DA-OBRA-ORIGINAL", "ISSN-ISBN",
      "IDIOMA-DA-OBRA-ORIGINAL", "EDITORA-DA-TRADUCAO", "CIDADE-DA-EDITORA",
      "NUMERO-DE-PAGINAS", "NUMERO-DA-EDICAO-REVISAO", "VOLUME", "FASCICULO",
      "SERIE",
    ],
    enumValues: {
      "NATUREZA": ["ARTIGO", "LIVRO", "OUTRO", "NAO_INFORMADO"],
    },
  },
  {
    label: "Artes Cênicas",
    path: "CURRICULO-VITAE/OUTRA-PRODUCAO/PRODUCAO-ARTISTICA-CULTURAL/ARTES-CENICAS",
    tagLattes: "ARTES-CENICAS",
    attrs: [
      "NATUREZA", "TITULO", "ANO", "PAIS", "IDIOMA", "TIPO-DE-EVENTO",
      "ATIVIDADE-DOS-AUTORES", "DATA-ESTREIA", "DATA-ENCERRAMENTO",
      "LOCAL-DE-ESTREIA", "PREMIACAO", "OBRA-DE-REFERENCIA",
      "AUTOR-DA-OBRA-DE-REFERENCIA", "ANO-DA-OBRA-DE-REFERENCIA", "DURACAO",
      "TEMPORADA", "INSTITUICAO-PROMOTORA-DO-EVENTO", "LOCAL-DO-EVENTO",
      "CIDADE-DO-EVENTO",
    ],
    enumValues: {},
  },
  {
    label: "Artes Visuais",
    path: "CURRICULO-VITAE/OUTRA-PRODUCAO/PRODUCAO-ARTISTICA-CULTURAL/ARTES-VISUAIS",
    tagLattes: "ARTES-VISUAIS",
    attrs: [
      "NATUREZA", "TITULO", "ANO", "PAIS", "IDIOMA", "PREMIACAO",
      "ATIVIDADE-DOS-AUTORES", "INSTITUICAO-PROMOTORA-DO-EVENTO",
      "LOCAL-DO-EVENTO", "CIDADE-DO-EVENTO", "TEMPORADA",
    ],
    enumValues: {},
  },
  {
    label: "Música",
    path: "CURRICULO-VITAE/OUTRA-PRODUCAO/PRODUCAO-ARTISTICA-CULTURAL/MUSICA",
    tagLattes: "MUSICA",
    attrs: [
      "NATUREZA", "TITULO", "ANO", "PAIS", "IDIOMA", "TIPO-DE-EVENTO",
      "ATIVIDADE-DOS-AUTORES", "FORMACAO-INSTRUMENTAL", "DATA-ESTREIA",
      "DATA-ENCERRAMENTO", "LOCAL-DE-ESTREIA", "PREMIACAO",
      "OBRA-DE-REFERENCIA", "AUTOR-DA-OBRA-DE-REFERENCIA",
      "ANO-DA-OBRA-DE-REFERENCIA", "DURACAO", "TEMPORADA",
      "INSTITUICAO-PROMOTORA-DO-EVENTO", "LOCAL-DO-EVENTO", "CIDADE-DO-EVENTO",
    ],
    enumValues: {},
  },
  {
    label: "Manutenção de Obra Artística",
    path: "CURRICULO-VITAE/PRODUCAO-TECNICA/DEMAIS-TIPOS-DE-PRODUCAO-TECNICA/MANUTENCAO-DE-OBRA-ARTISTICA",
    tagLattes: "MANUTENCAO-DE-OBRA-ARTISTICA",
    attrs: [
      "TIPO", "NATUREZA", "TITULO", "ANO", "PAIS", "IDIOMA", "DOI",
      "NOME-DA-OBRA", "AUTOR-DA-OBRA", "ANO-DA-OBRA", "ACERVO", "LOCAL",
      "CIDADE",
    ],
    enumValues: {},
  },
  {
    label: "Maquete",
    path: "CURRICULO-VITAE/PRODUCAO-TECNICA/DEMAIS-TIPOS-DE-PRODUCAO-TECNICA/MAQUETE",
    tagLattes: "MAQUETE",
    attrs: [
      "TITULO", "ANO", "PAIS", "IDIOMA", "DOI", "FINALIDADE",
      "OBJETO-REPRESENTADO", "MATERIAL-UTILIZADO", "INSTITUICAO-FINANCIADORA",
    ],
    enumValues: {},
  },
  {
    label: "Software",
    path: "CURRICULO-VITAE/PRODUCAO-TECNICA/SOFTWARE",
    tagLattes: "SOFTWARE",
    attrs: [
      "NATUREZA", "TITULO-DO-SOFTWARE", "ANO", "PAIS", "IDIOMA", "DOI",
      "FINALIDADE", "PLATAFORMA", "AMBIENTE", "DISPONIBILIDADE",
      "INSTITUICAO-FINANCIADORA", "TIPO-PATENTE", "TITULO-PATENTE",
      "DATA-PEDIDO-DE-DEPOSITO", "DATA-DE-CONCESSAO",
      "INSTITUICAO-DEPOSITO-REGISTRO", "NOME-DO-TITULAR", "NOME-DO-DEPOSITANTE",
    ],
    enumValues: {
      "NATUREZA": ["COMPUTACIONAL", "MULTIMIDIA", "OUTRO", "NAO_INFORMADO"],
      "DISPONIBILIDADE": ["RESTRITA", "IRRESTRITA", "NAO_INFORMADO"],
    },
  },
  {
    label: "Patente",
    path: "CURRICULO-VITAE/PRODUCAO-TECNICA/PATENTE",
    tagLattes: "PATENTE",
    attrs: [
      "TITULO", "ANO-DESENVOLVIMENTO", "PAIS", "FINALIDADE",
      "INSTITUICAO-FINANCIADORA", "CATEGORIA", "TIPO-PATENTE", "TITULO-PATENTE",
      "DATA-PEDIDO-DE-DEPOSITO", "DATA-DE-PEDIDO-DE-EXAME", "DATA-DE-CONCESSAO",
      "INSTITUICAO-DEPOSITO-REGISTRO", "NOME-DO-TITULAR", "NOME-DO-DEPOSITANTE",
      "STATUS-SITUACAO-PATENTE",
    ],
    enumValues: {
      "TIPO-PATENTE": [
        "PRIVILEGIO_DE_INOVACAO_PI", "MODELO_DE_UTILIDADE_MU", "DESENHO_INDUSTRIAL_DI",
        "MODELO_INDUSTRIAL_MI", "PATENTE_NO_EXTERIOR_PE", "PROGRAMA_DE_COMPUTADOR_PC",
        "CERTIFICADO_DE_ADICAO_CA", "CULTIVAR_PROTEGIDA_CTV",
        "MARCA_REGISTRADA_DE_PRODUTO_MPD", "MARCA_REGISTRADA_DE_SERVICO_MSV",
        "MARCA_REGISTRADA_COLETIVA_MCL", "MARCA_REGISTRADA_DE_CERTIFICACAO_MCT",
        "TOPOGRAFIA_DE_CIRCUITO_INTEGRADO_REGISTRADA_TCI",
        "MARCA_REGISTRADA_FIGURATIVA_MRF", "MARCA_REGISTRADA_NOMINATIVA_MRN",
        "MARCA_REGISTRADA_MISTA_MRM", "MARCA_REGISTRADA_TRIDIMENSIONAL_MRT",
      ],
    },
  },
  {
    label: "Orientações Concluídas para Doutorado",
    path: "CURRICULO-VITAE/OUTRA-PRODUCAO/ORIENTACOES-CONCLUIDAS/ORIENTACOES-CONCLUIDAS-PARA-DOUTORADO",
    tagLattes: "ORIENTACOES-CONCLUIDAS-PARA-DOUTORADO",
    attrs: [
      "NATUREZA", "TITULO", "ANO", "PAIS", "IDIOMA", "DOI",
      "TIPO-DE-ORIENTACAO", "NOME-DO-ORIENTADO", "NOME-DA-INSTITUICAO",
      "NOME-ORGAO", "NOME-DO-CURSO", "NOME-DA-AGENCIA", "NUMERO-DE-PAGINAS",
    ],
    enumValues: {
      "TIPO-DE-ORIENTACAO": ["ORIENTADOR_PRINCIPAL", "CO_ORIENTADOR"],
    },
  },
  {
    label: "Orientações Concluídas para Mestrado",
    path: "CURRICULO-VITAE/OUTRA-PRODUCAO/ORIENTACOES-CONCLUIDAS/ORIENTACOES-CONCLUIDAS-PARA-MESTRADO",
    tagLattes: "ORIENTACOES-CONCLUIDAS-PARA-MESTRADO",
    attrs: [
      "NATUREZA", "TIPO", "TITULO", "ANO", "PAIS", "IDIOMA", "DOI",
      "TIPO-DE-ORIENTACAO", "NOME-DO-ORIENTADO", "NOME-DA-INSTITUICAO",
      "NOME-ORGAO", "NOME-DO-CURSO", "NOME-DA-AGENCIA", "NUMERO-DE-PAGINAS",
    ],
    enumValues: {
      "TIPO": ["ACADEMICO", "PROFISSIONALIZANTE", "NAO_INFORMADO"],
      "TIPO-DE-ORIENTACAO": ["ORIENTADOR_PRINCIPAL", "CO_ORIENTADOR"],
    },
  },
  {
    label: "Orientações Concluídas para Pós-Doutorado",
    path: "CURRICULO-VITAE/OUTRA-PRODUCAO/ORIENTACOES-CONCLUIDAS/ORIENTACOES-CONCLUIDAS-PARA-POS-DOUTORADO",
    tagLattes: "ORIENTACOES-CONCLUIDAS-PARA-POS-DOUTORADO",
    attrs: [
      "NATUREZA", "TITULO", "ANO", "PAIS", "IDIOMA", "DOI",
      "TIPO-DE-ORIENTACAO", "NOME-DO-ORIENTADO", "NOME-DA-INSTITUICAO",
      "NOME-ORGAO", "NOME-DO-CURSO", "NOME-DA-AGENCIA", "NUMERO-DE-PAGINAS",
    ],
    enumValues: {
      "TIPO-DE-ORIENTACAO": ["ORIENTADOR_PRINCIPAL", "CO_ORIENTADOR"],
    },
  },
  {
    label: "Outras Orientações Concluídas",
    path: "CURRICULO-VITAE/OUTRA-PRODUCAO/ORIENTACOES-CONCLUIDAS/OUTRAS-ORIENTACOES-CONCLUIDAS",
    tagLattes: "OUTRAS-ORIENTACOES-CONCLUIDAS",
    attrs: [
      "NATUREZA", "TIPO", "TITULO", "ANO", "PAIS", "IDIOMA", "DOI",
      "NOME-DO-ORIENTADO", "NOME-DA-INSTITUICAO", "NOME-ORGAO",
      "NOME-DO-CURSO", "NOME-DA-AGENCIA", "TIPO-DE-ORIENTACAO-CONCLUIDA",
      "NUMERO-DE-PAGINAS",
    ],
    enumValues: {
      "NATUREZA": [
        "MONOGRAFIA_DE_CONCLUSAO_DE_CURSO_APERFEICOAMENTO_E_ESPECIALIZACAO",
        "TRABALHO_DE_CONCLUSAO_DE_CURSO_GRADUACAO",
        "INICIACAO_CIENTIFICA",
        "ORIENTACAO-DE-OUTRA-NATUREZA",
      ],
    },
  },
  {
    label: "Projeto de Pesquisa",
    path: "CURRICULO-VITAE/DADOS-GERAIS/ATUACOES-PROFISSIONAIS/ATUACAO-PROFISSIONAL/ATIVIDADES-DE-PARTICIPACAO-EM-PROJETO/PARTICIPACAO-EM-PROJETO/PROJETO-DE-PESQUISA",
    tagLattes: "PROJETO-DE-PESQUISA",
    attrs: [
      "ANO-INICIO", "ANO-FIM", "NOME-DO-PROJETO", "SITUACAO", "NATUREZA",
      "DESCRICAO-DO-PROJETO", "NOME-INSTITUICAO",
    ],
    enumValues: {
      "SITUACAO": ["EM_ANDAMENTO", "DESATIVADO", "CONCLUIDO"],
      "NATUREZA": ["DESENVOLVIMENTO", "EXTENSAO", "PESQUISA", "ENSINO", "OUTRA"],
    },
  },
  {
    label: "Vínculos",
    path: "CURRICULO-VITAE/DADOS-GERAIS/ATUACOES-PROFISSIONAIS/ATUACAO-PROFISSIONAL/VINCULOS",
    tagLattes: "VINCULOS",
    attrs: [
      "TIPO-DE-VINCULO", "ENQUADRAMENTO-FUNCIONAL", "CARGA-HORARIA-SEMANAL",
      "FLAG-DEDICACAO-EXCLUSIVA", "MES-INICIO", "ANO-INICIO", "MES-FIM", "ANO-FIM",
      "OUTRAS-INFORMACOES", "FLAG-VINCULO-EMPREGATICIO", "OUTRO-VINCULO-INFORMADO",
      "OUTRO-ENQUADRAMENTO-FUNCIONAL-INFORMADO",
    ],
    enumValues: {
      "TIPO-DE-VINCULO": [
        "SERVIDOR_PUBLICO_OU_CELETISTA", "SERVIDOR_PUBLICO", "CELETISTA",
        "PROFESSOR_VISITANTE", "COLABORADOR", "BOLSISTA_RECEM_DOUTOR", "OUTRO", "LIVRE",
      ],
      "ENQUADRAMENTO-FUNCIONAL": ["PROFESSOR_TITULAR", "OUTRO", "LIVRE"],
      "FLAG-DEDICACAO-EXCLUSIVA": ["SIM", "NAO"],
      "FLAG-VINCULO-EMPREGATICIO": ["SIM", "NAO"],
    },
  },
  {
    label: "Ensino",
    path: "CURRICULO-VITAE/DADOS-GERAIS/ATUACOES-PROFISSIONAIS/ATUACAO-PROFISSIONAL/ATIVIDADES-DE-ENSINO/ENSINO",
    tagLattes: "ENSINO",
    attrs: [
      "TIPO-ENSINO", "MES-INICIO", "ANO-INICIO", "MES-FIM", "ANO-FIM",
      "NOME-ORGAO", "NOME-CURSO", "DISCIPLINA",
    ],
    enumValues: {
      "TIPO-ENSINO": [
        "GRADUACAO", "POS-GRADUACAO", "ESPECIALIZACAO", "APERFEICOAMENTO",
        "ENSINO-FUNDAMENTAL", "ENSINO-MEDIO", "OUTRO",
      ],
    },
  },
  {
    label: "Pesquisa e Desenvolvimento",
    path: "CURRICULO-VITAE/DADOS-GERAIS/ATUACOES-PROFISSIONAIS/ATUACAO-PROFISSIONAL/ATIVIDADES-DE-PESQUISA-E-DESENVOLVIMENTO/PESQUISA-E-DESENVOLVIMENTO",
    tagLattes: "PESQUISA-E-DESENVOLVIMENTO",
    attrs: [
      "MES-INICIO", "ANO-INICIO", "MES-FIM", "ANO-FIM", "NOME-ORGAO",
      "NOME-UNIDADE",
    ],
    enumValues: {},
  },
  {
    label: "Extensão Universitária",
    path: "CURRICULO-VITAE/DADOS-GERAIS/ATUACOES-PROFISSIONAIS/ATUACAO-PROFISSIONAL/ATIVIDADES-DE-EXTENSAO-UNIVERSITARIA/EXTENSAO-UNIVERSITARIA",
    tagLattes: "EXTENSAO-UNIVERSITARIA",
    attrs: [
      "MES-INICIO", "ANO-INICIO", "MES-FIM", "ANO-FIM", "NOME-ORGAO",
      "NOME-UNIDADE", "ATIVIDADE-DE-EXTENSAO-REALIZADA",
    ],
    enumValues: {},
  },
  // DADOS-COMPLEMENTARES/PARTICIPACAO-EM-EVENTOS-CONGRESSOS: cada subtipo repete o
  // mesmo par DADOS-BASICOS-DA-PARTICIPACAO-EM-X / DETALHAMENTO-DA-PARTICIPACAO-EM-X.
  {
    label: "Participação em Congresso",
    path: "CURRICULO-VITAE/DADOS-COMPLEMENTARES/PARTICIPACAO-EM-EVENTOS-CONGRESSOS/PARTICIPACAO-EM-CONGRESSO",
    tagLattes: "PARTICIPACAO-EM-CONGRESSO",
    attrs: [
      "NATUREZA", "TITULO", "ANO", "PAIS", "IDIOMA", "MEIO-DE-DIVULGACAO",
      "HOME-PAGE-DO-TRABALHO", "FLAG-RELEVANCIA", "TIPO-PARTICIPACAO",
      "FORMA-PARTICIPACAO", "DOI", "TITULO-INGLES", "FLAG-DIVULGACAO-CIENTIFICA",
      "NOME-DO-EVENTO", "CODIGO-INSTITUICAO", "NOME-INSTITUICAO",
      "LOCAL-DO-EVENTO", "CIDADE-DO-EVENTO", "NOME-DO-EVENTO-INGLES",
    ],
    enumValues: {
      "MEIO-DE-DIVULGACAO": [
        "IMPRESSO", "WEB", "MEIO_MAGNETICO", "MEIO_DIGITAL", "FILME",
        "HIPERTEXTO", "OUTRO", "VARIOS", "NAO_INFORMADO",
      ],
      "FLAG-RELEVANCIA": ["SIM", "NAO"],
      "FLAG-DIVULGACAO-CIENTIFICA": ["SIM", "NAO"],
    },
  },
  {
    label: "Participação em Feira",
    path: "CURRICULO-VITAE/DADOS-COMPLEMENTARES/PARTICIPACAO-EM-EVENTOS-CONGRESSOS/PARTICIPACAO-EM-FEIRA",
    tagLattes: "PARTICIPACAO-EM-FEIRA",
    attrs: [
      "NATUREZA", "TITULO", "ANO", "PAIS", "IDIOMA", "MEIO-DE-DIVULGACAO",
      "HOME-PAGE-DO-TRABALHO", "FLAG-RELEVANCIA", "TIPO-PARTICIPACAO",
      "FORMA-PARTICIPACAO", "DOI", "TITULO-INGLES", "FLAG-DIVULGACAO-CIENTIFICA",
      "NOME-DO-EVENTO", "CODIGO-INSTITUICAO", "NOME-INSTITUICAO",
      "LOCAL-DO-EVENTO", "CIDADE-DO-EVENTO", "NOME-DO-EVENTO-INGLES",
    ],
    enumValues: {
      "MEIO-DE-DIVULGACAO": [
        "IMPRESSO", "WEB", "MEIO_MAGNETICO", "MEIO_DIGITAL", "FILME",
        "HIPERTEXTO", "OUTRO", "VARIOS", "NAO_INFORMADO",
      ],
      "FLAG-RELEVANCIA": ["SIM", "NAO"],
      "FLAG-DIVULGACAO-CIENTIFICA": ["SIM", "NAO"],
    },
  },
  {
    label: "Participação em Seminário",
    path: "CURRICULO-VITAE/DADOS-COMPLEMENTARES/PARTICIPACAO-EM-EVENTOS-CONGRESSOS/PARTICIPACAO-EM-SEMINARIO",
    tagLattes: "PARTICIPACAO-EM-SEMINARIO",
    attrs: [
      "NATUREZA", "TITULO", "ANO", "PAIS", "IDIOMA", "MEIO-DE-DIVULGACAO",
      "HOME-PAGE-DO-TRABALHO", "FLAG-RELEVANCIA", "TIPO-PARTICIPACAO",
      "FORMA-PARTICIPACAO", "DOI", "TITULO-INGLES", "FLAG-DIVULGACAO-CIENTIFICA",
      "NOME-DO-EVENTO", "CODIGO-INSTITUICAO", "NOME-INSTITUICAO",
      "LOCAL-DO-EVENTO", "CIDADE-DO-EVENTO", "NOME-DO-EVENTO-INGLES",
    ],
    enumValues: {
      "MEIO-DE-DIVULGACAO": [
        "IMPRESSO", "WEB", "MEIO_MAGNETICO", "MEIO_DIGITAL", "FILME",
        "HIPERTEXTO", "OUTRO", "VARIOS", "NAO_INFORMADO",
      ],
      "FLAG-RELEVANCIA": ["SIM", "NAO"],
      "FLAG-DIVULGACAO-CIENTIFICA": ["SIM", "NAO"],
    },
  },
  {
    label: "Participação em Simpósio",
    path: "CURRICULO-VITAE/DADOS-COMPLEMENTARES/PARTICIPACAO-EM-EVENTOS-CONGRESSOS/PARTICIPACAO-EM-SIMPOSIO",
    tagLattes: "PARTICIPACAO-EM-SIMPOSIO",
    attrs: [
      "NATUREZA", "TITULO", "ANO", "PAIS", "IDIOMA", "MEIO-DE-DIVULGACAO",
      "HOME-PAGE-DO-TRABALHO", "FLAG-RELEVANCIA", "TIPO-PARTICIPACAO",
      "FORMA-PARTICIPACAO", "DOI", "TITULO-INGLES", "FLAG-DIVULGACAO-CIENTIFICA",
      "NOME-DO-EVENTO", "CODIGO-INSTITUICAO", "NOME-INSTITUICAO",
      "LOCAL-DO-EVENTO", "CIDADE-DO-EVENTO", "NOME-DO-EVENTO-INGLES",
    ],
    enumValues: {
      "MEIO-DE-DIVULGACAO": [
        "IMPRESSO", "WEB", "MEIO_MAGNETICO", "MEIO_DIGITAL", "FILME",
        "HIPERTEXTO", "OUTRO", "VARIOS", "NAO_INFORMADO",
      ],
      "FLAG-RELEVANCIA": ["SIM", "NAO"],
      "FLAG-DIVULGACAO-CIENTIFICA": ["SIM", "NAO"],
    },
  },
  {
    label: "Participação em Oficina",
    path: "CURRICULO-VITAE/DADOS-COMPLEMENTARES/PARTICIPACAO-EM-EVENTOS-CONGRESSOS/PARTICIPACAO-EM-OFICINA",
    tagLattes: "PARTICIPACAO-EM-OFICINA",
    attrs: [
      "NATUREZA", "TITULO", "ANO", "PAIS", "IDIOMA", "MEIO-DE-DIVULGACAO",
      "HOME-PAGE-DO-TRABALHO", "FLAG-RELEVANCIA", "TIPO-PARTICIPACAO",
      "FORMA-PARTICIPACAO", "DOI", "TITULO-INGLES", "FLAG-DIVULGACAO-CIENTIFICA",
      "NOME-DO-EVENTO", "CODIGO-INSTITUICAO", "NOME-INSTITUICAO",
      "LOCAL-DO-EVENTO", "CIDADE-DO-EVENTO", "NOME-DO-EVENTO-INGLES",
    ],
    enumValues: {
      "MEIO-DE-DIVULGACAO": [
        "IMPRESSO", "WEB", "MEIO_MAGNETICO", "MEIO_DIGITAL", "FILME",
        "HIPERTEXTO", "OUTRO", "VARIOS", "NAO_INFORMADO",
      ],
      "FLAG-RELEVANCIA": ["SIM", "NAO"],
      "FLAG-DIVULGACAO-CIENTIFICA": ["SIM", "NAO"],
    },
  },
  {
    label: "Participação em Encontro",
    path: "CURRICULO-VITAE/DADOS-COMPLEMENTARES/PARTICIPACAO-EM-EVENTOS-CONGRESSOS/PARTICIPACAO-EM-ENCONTRO",
    tagLattes: "PARTICIPACAO-EM-ENCONTRO",
    attrs: [
      "NATUREZA", "TITULO", "ANO", "PAIS", "IDIOMA", "MEIO-DE-DIVULGACAO",
      "HOME-PAGE-DO-TRABALHO", "FLAG-RELEVANCIA", "TIPO-PARTICIPACAO",
      "FORMA-PARTICIPACAO", "DOI", "TITULO-INGLES", "FLAG-DIVULGACAO-CIENTIFICA",
      "NOME-DO-EVENTO", "CODIGO-INSTITUICAO", "NOME-INSTITUICAO",
      "LOCAL-DO-EVENTO", "CIDADE-DO-EVENTO", "NOME-DO-EVENTO-INGLES",
    ],
    enumValues: {
      "MEIO-DE-DIVULGACAO": [
        "IMPRESSO", "WEB", "MEIO_MAGNETICO", "MEIO_DIGITAL", "FILME",
        "HIPERTEXTO", "OUTRO", "VARIOS", "NAO_INFORMADO",
      ],
      "FLAG-RELEVANCIA": ["SIM", "NAO"],
      "FLAG-DIVULGACAO-CIENTIFICA": ["SIM", "NAO"],
    },
  },
  {
    label: "Participação em Exposição",
    path: "CURRICULO-VITAE/DADOS-COMPLEMENTARES/PARTICIPACAO-EM-EVENTOS-CONGRESSOS/PARTICIPACAO-EM-EXPOSICAO",
    tagLattes: "PARTICIPACAO-EM-EXPOSICAO",
    attrs: [
      "NATUREZA", "TITULO", "ANO", "PAIS", "IDIOMA", "MEIO-DE-DIVULGACAO",
      "HOME-PAGE-DO-TRABALHO", "FLAG-RELEVANCIA", "TIPO-PARTICIPACAO",
      "FORMA-PARTICIPACAO", "DOI", "TITULO-INGLES", "FLAG-DIVULGACAO-CIENTIFICA",
      "NOME-DO-EVENTO", "CODIGO-INSTITUICAO", "NOME-INSTITUICAO",
      "LOCAL-DO-EVENTO", "CIDADE-DO-EVENTO", "NOME-DO-EVENTO-INGLES",
    ],
    enumValues: {
      "MEIO-DE-DIVULGACAO": [
        "IMPRESSO", "WEB", "MEIO_MAGNETICO", "MEIO_DIGITAL", "FILME",
        "HIPERTEXTO", "OUTRO", "VARIOS", "NAO_INFORMADO",
      ],
      "FLAG-RELEVANCIA": ["SIM", "NAO"],
      "FLAG-DIVULGACAO-CIENTIFICA": ["SIM", "NAO"],
    },
  },
  {
    label: "Participação em Olimpíada",
    path: "CURRICULO-VITAE/DADOS-COMPLEMENTARES/PARTICIPACAO-EM-EVENTOS-CONGRESSOS/PARTICIPACAO-EM-OLIMPIADA",
    tagLattes: "PARTICIPACAO-EM-OLIMPIADA",
    attrs: [
      "NATUREZA", "TITULO", "ANO", "PAIS", "IDIOMA", "MEIO-DE-DIVULGACAO",
      "HOME-PAGE-DO-TRABALHO", "FLAG-RELEVANCIA", "TIPO-PARTICIPACAO",
      "FORMA-PARTICIPACAO", "DOI", "TITULO-INGLES", "FLAG-DIVULGACAO-CIENTIFICA",
      "NOME-DO-EVENTO", "CODIGO-INSTITUICAO", "NOME-INSTITUICAO",
      "LOCAL-DO-EVENTO", "CIDADE-DO-EVENTO", "NOME-DO-EVENTO-INGLES",
    ],
    enumValues: {
      "MEIO-DE-DIVULGACAO": [
        "IMPRESSO", "WEB", "MEIO_MAGNETICO", "MEIO_DIGITAL", "FILME",
        "HIPERTEXTO", "OUTRO", "VARIOS", "NAO_INFORMADO",
      ],
      "FLAG-RELEVANCIA": ["SIM", "NAO"],
      "FLAG-DIVULGACAO-CIENTIFICA": ["SIM", "NAO"],
    },
  },
  {
    label: "Outras Participações em Eventos/Congressos",
    path: "CURRICULO-VITAE/DADOS-COMPLEMENTARES/PARTICIPACAO-EM-EVENTOS-CONGRESSOS/OUTRAS-PARTICIPACOES-EM-EVENTOS-CONGRESSOS",
    tagLattes: "OUTRAS-PARTICIPACOES-EM-EVENTOS-CONGRESSOS",
    attrs: [
      "NATUREZA", "TITULO", "ANO", "PAIS", "IDIOMA", "MEIO-DE-DIVULGACAO",
      "HOME-PAGE-DO-TRABALHO", "FLAG-RELEVANCIA", "TIPO-PARTICIPACAO",
      "FORMA-PARTICIPACAO", "DOI", "TITULO-INGLES", "FLAG-DIVULGACAO-CIENTIFICA",
      "NOME-DO-EVENTO", "CODIGO-INSTITUICAO", "NOME-INSTITUICAO",
      "LOCAL-DO-EVENTO", "CIDADE-DO-EVENTO", "NOME-DO-EVENTO-INGLES",
    ],
    enumValues: {
      "MEIO-DE-DIVULGACAO": [
        "IMPRESSO", "WEB", "MEIO_MAGNETICO", "MEIO_DIGITAL", "FILME",
        "HIPERTEXTO", "OUTRO", "VARIOS", "NAO_INFORMADO",
      ],
      "FLAG-RELEVANCIA": ["SIM", "NAO"],
      "FLAG-DIVULGACAO-CIENTIFICA": ["SIM", "NAO"],
    },
  },
];
